#!/usr/bin/env bash



# Kill already running process
_ps=(waybar mako mpd xfce-polkit)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done


# Polkit agent
bash /usr/lib/xfce-polkit/xfce-polkit &
# Lauch statusbar (waybar)
bash ~/.config/hypr/scripts/statusbar &


# Set wallpaper
#mpvpaper -vs -o "no-audio loop" eDP-1 /home/rick/Downloads/bg.mp4
swaybg --image /home/rick/.config/hypr/wallpapers/roses_bush_bloom_128901_3840x2400.jpg &
# Apply themes
bash ~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
bash ~/.config/hypr/scripts/notifications &

spicetify config color_scheme samourai; spicetify apply &





# Start mpd
exec mpd
