#!/usr/bin/env bash



# Kill already running process
_ps=(waybar mako mpd xfce-polkit)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done


# Polkit agent
bash /usr/lib/xfce-polkit/xfce-polkit &
# Lauch statusbar (waybar)
bash ~/.config/hypr/scripts/statusbar &

 
# Set wallpaper
mpvpaper -o "no-audio --loop-playlist shuffle" '*' /home/rick/Downloads/ok.mp4 &
#swaybg --image /home/rick/.config/hypr/ok.png &
# Apply themes
bash ~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
bash ~/.config/hypr/scripts/notifications &

spicetify config color_scheme samourai; spicetify apply &





# Start mpd
exec mpd
